// NAICS Code structure for eligible sectors from 2022 NAICS Structure
export interface NAICSCode {
  code: string;
  title: string;
  level: number;
  parent: string;
}

// Facility Sectors (2-digit codes) - Alphabetically sorted
export const FACILITY_SECTORS: NAICSCode[] = [
  { code: "56", title: "Administrative and Support and Waste Management and Remediation Services", level: 2, parent: "" },
  { code: "11", title: "Agriculture, Forestry, Fishing and Hunting", level: 2, parent: "" },
  { code: "23", title: "Construction", level: 2, parent: "" },
  { code: "31-33", title: "Manufacturing", level: 2, parent: "" },
  { code: "21", title: "Mining, Quarrying, and Oil and Gas Extraction", level: 2, parent: "" },
  { code: "48", title: "Transportation and Warehousing", level: 2, parent: "" },
  { code: "22", title: "Utilities", level: 2, parent: "" },
];

// Facility Categories (3-digit codes) - Alphabetically sorted within each sector
export const FACILITY_CATEGORIES: NAICSCode[] = [
  { code: "561", title: "Administrative and Support Services", level: 3, parent: "56" },
  { code: "481", title: "Air Transportation", level: 3, parent: "48" },
  { code: "112", title: "Animal Production and Aquaculture", level: 3, parent: "11" },
  { code: "315", title: "Apparel Manufacturing", level: 3, parent: "31-33" },
  { code: "312", title: "Beverage and Tobacco Product Manufacturing", level: 3, parent: "31-33" },
  { code: "325", title: "Chemical Manufacturing", level: 3, parent: "31-33" },
  { code: "334", title: "Computer and Electronic Product Manufacturing", level: 3, parent: "31-33" },
  { code: "236", title: "Construction of Buildings", level: 3, parent: "23" },
  { code: "111", title: "Crop Production", level: 3, parent: "11" },
  { code: "335", title: "Electrical Equipment, Appliance, and Component Manufacturing", level: 3, parent: "31-33" },
  { code: "332", title: "Fabricated Metal Product Manufacturing", level: 3, parent: "31-33" },
  { code: "114", title: "Fishing, Hunting and Trapping", level: 3, parent: "11" },
  { code: "311", title: "Food Manufacturing", level: 3, parent: "31-33" },
  { code: "113", title: "Forestry and Logging", level: 3, parent: "11" },
  { code: "337", title: "Furniture and Related Product Manufacturing", level: 3, parent: "31-33" },
  { code: "237", title: "Heavy and Civil Engineering Construction", level: 3, parent: "23" },
  { code: "316", title: "Leather and Allied Product Manufacturing", level: 3, parent: "31-33" },
  { code: "333", title: "Machinery Manufacturing", level: 3, parent: "31-33" },
  { code: "212", title: "Mining (except Oil and Gas)", level: 3, parent: "21" },
  { code: "339", title: "Miscellaneous Manufacturing", level: 3, parent: "31-33" },
  { code: "327", title: "Nonmetallic Mineral Product Manufacturing", level: 3, parent: "31-33" },
  { code: "211", title: "Oil and Gas Extraction", level: 3, parent: "21" },
  { code: "322", title: "Paper Manufacturing", level: 3, parent: "31-33" },
  { code: "324", title: "Petroleum and Coal Products Manufacturing", level: 3, parent: "31-33" },
  { code: "486", title: "Pipeline Transportation", level: 3, parent: "48" },
  { code: "326", title: "Plastics and Rubber Products Manufacturing", level: 3, parent: "31-33" },
  { code: "331", title: "Primary Metal Manufacturing", level: 3, parent: "31-33" },
  { code: "323", title: "Printing and Related Support Activities", level: 3, parent: "31-33" },
  { code: "482", title: "Rail Transportation", level: 3, parent: "48" },
  { code: "487", title: "Scenic and Sightseeing Transportation", level: 3, parent: "48" },
  { code: "238", title: "Specialty Trade Contractors", level: 3, parent: "23" },
  { code: "115", title: "Support Activities for Agriculture and Forestry", level: 3, parent: "11" },
  { code: "213", title: "Support Activities for Mining", level: 3, parent: "21" },
  { code: "488", title: "Support Activities for Transportation", level: 3, parent: "48" },
  { code: "313", title: "Textile Mills", level: 3, parent: "31-33" },
  { code: "314", title: "Textile Product Mills", level: 3, parent: "31-33" },
  { code: "485", title: "Transit and Ground Passenger Transportation", level: 3, parent: "48" },
  { code: "336", title: "Transportation Equipment Manufacturing", level: 3, parent: "31-33" },
  { code: "484", title: "Truck Transportation", level: 3, parent: "48" },
  { code: "221", title: "Utilities", level: 3, parent: "22" },
  { code: "562", title: "Waste Management and Remediation Services", level: 3, parent: "56" },
  { code: "483", title: "Water Transportation", level: 3, parent: "48" },
  { code: "321", title: "Wood Product Manufacturing", level: 3, parent: "31-33" },
];

// Facility Types (6-digit codes) - Alphabetically sorted within each category
export const FACILITY_TYPES: NAICSCode[] = [
  { code: "327910", title: "Abrasive Product Manufacturing", level: 6, parent: "327" },
  { code: "325520", title: "Adhesive Manufacturing", level: 6, parent: "325" },
  { code: "488111", title: "Air Traffic Control", level: 6, parent: "488" },
  { code: "333912", title: "Air and Gas Compressor Manufacturing", level: 6, parent: "333" },
  { code: "333415", title: "Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing", level: 6, parent: "333" },
  { code: "336412", title: "Aircraft Engine and Engine Parts Manufacturing", level: 6, parent: "336" },
  { code: "336411", title: "Aircraft Manufacturing", level: 6, parent: "336" },
  { code: "112990", title: "All Other Animal Production", level: 6, parent: "112" },
  { code: "325199", title: "All Other Basic Organic Chemical Manufacturing", level: 6, parent: "325" },
  { code: "561499", title: "All Other Business Support Services", level: 6, parent: "561" },
  { code: "322299", title: "All Other Converted Paper Product Manufacturing", level: 6, parent: "322" },
  { code: "111199", title: "All Other Grain Farming", level: 6, parent: "111" },
  { code: "333248", title: "All Other Industrial Machinery Manufacturing", level: 6, parent: "333" },
  { code: "325998", title: "All Other Miscellaneous Chemical Product and Preparation Manufacturing", level: 6, parent: "325" },
  { code: "111998", title: "All Other Miscellaneous Crop Farming", level: 6, parent: "111" },
  { code: "335999", title: "All Other Miscellaneous Electrical Equipment and Component Manufacturing", level: 6, parent: "335" },
  { code: "332999", title: "All Other Miscellaneous Fabricated Metal Product Manufacturing", level: 6, parent: "332" },
  { code: "311999", title: "All Other Miscellaneous Food Manufacturing", level: 6, parent: "311" },
  { code: "333998", title: "All Other Miscellaneous General Purpose Machinery Manufacturing", level: 6, parent: "333" },
  { code: "339999", title: "All Other Miscellaneous Manufacturing", level: 6, parent: "339" },
  { code: "327999", title: "All Other Miscellaneous Nonmetallic Mineral Product Manufacturing", level: 6, parent: "327" },
  { code: "314999", title: "All Other Miscellaneous Textile Product Mills", level: 6, parent: "314" },
  { code: "562998", title: "All Other Miscellaneous Waste Management Services", level: 6, parent: "562" },
  { code: "321999", title: "All Other Miscellaneous Wood Product Manufacturing", level: 6, parent: "321" },
  { code: "324199", title: "All Other Petroleum and Coal Products Manufacturing", level: 6, parent: "324" },
  { code: "486990", title: "All Other Pipeline Transportation", level: 6, parent: "486" },
  { code: "326199", title: "All Other Plastics Product Manufacturing", level: 6, parent: "326" },
  { code: "326299", title: "All Other Rubber Product Manufacturing", level: 6, parent: "326" },
  { code: "238990", title: "All Other Specialty Trade Contractors", level: 6, parent: "238" },
  { code: "488999", title: "All Other Support Activities for Transportation", level: 6, parent: "488" },
  { code: "561990", title: "All Other Support Services", level: 6, parent: "561" },
  { code: "485999", title: "All Other Transit and Ground Passenger Transportation", level: 6, parent: "485" },
  { code: "336999", title: "All Other Transportation Equipment Manufacturing", level: 6, parent: "336" },
  { code: "561599", title: "All Other Travel Arrangement and Reservation Services", level: 6, parent: "561" },
  { code: "331313", title: "Alumina Refining and Primary Aluminum Production", level: 6, parent: "331" },
  { code: "331524", title: "Aluminum Foundries (except Die-Casting)", level: 6, parent: "331" },
  { code: "331315", title: "Aluminum Sheet, Plate, and Foil Manufacturing", level: 6, parent: "331" },
  { code: "332993", title: "Ammunition (except Small Arms) Manufacturing", level: 6, parent: "332" },
  { code: "334516", title: "Analytical Laboratory Instrument Manufacturing", level: 6, parent: "334" },
  { code: "311611", title: "Animal (except Poultry) Slaughtering", level: 6, parent: "311" },
  { code: "112910", title: "Apiculture", level: 6, parent: "112" },
  { code: "315990", title: "Apparel Accessories and Other Apparel Manufacturing", level: 6, parent: "315" },
  { code: "315120", title: "Apparel Knitting Mills", level: 6, parent: "315" },
  { code: "111331", title: "Apple Orchards", level: 6, parent: "111" },
  { code: "561613", title: "Armored Car Services", level: 6, parent: "561" },
  { code: "325220", title: "Artificial and Synthetic Fibers and Filaments Manufacturing", level: 6, parent: "325" },
  { code: "324121", title: "Asphalt Paving Mixture and Block Manufacturing", level: 6, parent: "324" },
  { code: "324122", title: "Asphalt Shingle and Coating Materials Manufacturing", level: 6, parent: "324" },
  { code: "334310", title: "Audio and Video Equipment Manufacturing", level: 6, parent: "334" },
  { code: "334512", title: "Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use", level: 6, parent: "334" },
  { code: "336110", title: "Automobile and Light Duty Motor Vehicle Manufacturing", level: 6, parent: "336" },
  { code: "332991", title: "Ball and Roller Bearing Manufacturing", level: 6, parent: "332" },
  { code: "334412", title: "Bare Printed Circuit Board Manufacturing", level: 6, parent: "334" },
  { code: "335910", title: "Battery Manufacturing", level: 6, parent: "335" },
  { code: "112111", title: "Beef Cattle Ranching and Farming", level: 6, parent: "112" },
  { code: "311313", title: "Beet Sugar Manufacturing", level: 6, parent: "311" },
  { code: "111334", title: "Berry (except Strawberry) Farming", level: 6, parent: "111" },
  { code: "325414", title: "Biological Product (except Diagnostic) Manufacturing", level: 6, parent: "325" },
  { code: "221117", title: "Biomass Electric Power Generation", level: 6, parent: "221" },
  { code: "337920", title: "Blind and Shade Manufacturing", level: 6, parent: "337" },
  { code: "336612", title: "Boat Building", level: 6, parent: "336" },
  { code: "332722", title: "Bolt, Nut, Screw, Rivet, and Washer Manufacturing", level: 6, parent: "332" },
  { code: "323117", title: "Books Printing", level: 6, parent: "323" },
  { code: "312112", title: "Bottled Water Manufacturing", level: 6, parent: "312" },
  { code: "311230", title: "Breakfast Cereal Manufacturing", level: 6, parent: "311" },
  { code: "312120", title: "Breweries", level: 6, parent: "312" },
  { code: "313210", title: "Broadwoven Fabric Mills", level: 6, parent: "313" },
  { code: "112320", title: "Broilers and Other Meat Type Chicken Production", level: 6, parent: "112" },
  { code: "339994", title: "Broom, Brush, and Mop Manufacturing", level: 6, parent: "339" },
  { code: "339995", title: "Burial Casket Manufacturing", level: 6, parent: "339" },
  { code: "485113", title: "Bus and Other Motor Vehicle Transit Systems", level: 6, parent: "485" },
  { code: "311314", title: "Cane Sugar Manufacturing", level: 6, parent: "311" },
  { code: "334416", title: "Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing", level: 6, parent: "334" },
  { code: "335991", title: "Carbon and Graphite Product Manufacturing", level: 6, parent: "335" },
  { code: "314110", title: "Carpet and Rug Mills", level: 6, parent: "314" },
  { code: "561740", title: "Carpet and Upholstery Cleaning Services", level: 6, parent: "561" },
  { code: "112112", title: "Cattle Feedlots", level: 6, parent: "112" },
  { code: "327310", title: "Cement Manufacturing", level: 6, parent: "327" },
  { code: "485510", title: "Charter Bus Industry", level: 6, parent: "485" },
  { code: "311513", title: "Cheese Manufacturing", level: 6, parent: "311" },
  { code: "112310", title: "Chicken Egg Production", level: 6, parent: "112" },
  { code: "311351", title: "Chocolate and Confectionery Manufacturing from Cacao Beans", level: 6, parent: "311" },
  { code: "111320", title: "Citrus (except Orange) Groves", level: 6, parent: "111" },
  { code: "327120", title: "Clay Building Material and Refractories Manufacturing", level: 6, parent: "327" },
  { code: "483113", title: "Coastal and Great Lakes Freight Transportation", level: 6, parent: "483" },
  { code: "483114", title: "Coastal and Great Lakes Passenger Transportation", level: 6, parent: "483" },
  { code: "311920", title: "Coffee and Tea Manufacturing", level: 6, parent: "311" },
  { code: "561440", title: "Collection Agencies", level: 6, parent: "561" },
  { code: "311812", title: "Commercial Bakeries", level: 6, parent: "311" },
  { code: "323111", title: "Commercial Printing (except Screen and Books)", level: 6, parent: "323" },
  { code: "323113", title: "Commercial Screen Printing", level: 6, parent: "323" },
  { code: "236220", title: "Commercial and Institutional Building Construction", level: 6, parent: "236" },
  { code: "333310", title: "Commercial and Service Industry Machinery Manufacturing", level: 6, parent: "333" },
  { code: "335132", title: "Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing", level: 6, parent: "335" },
  { code: "485112", title: "Commuter Rail Systems", level: 6, parent: "485" },
  { code: "325315", title: "Compost Manufacturing", level: 6, parent: "325" },
  { code: "334112", title: "Computer Storage Device Manufacturing", level: 6, parent: "334" },
  { code: "334118", title: "Computer Terminal and Other Computer Peripheral Equipment Manufacturing", level: 6, parent: "334" },
  { code: "327331", title: "Concrete Block and Brick Manufacturing", level: 6, parent: "327" },
  { code: "327332", title: "Concrete Pipe Manufacturing", level: 6, parent: "327" },
  { code: "311352", title: "Confectionery Manufacturing from Purchased Chocolate", level: 6, parent: "311" },
  { code: "333120", title: "Construction Machinery Manufacturing", level: 6, parent: "333" },
  { code: "212321", title: "Construction Sand and Gravel Mining", level: 6, parent: "212" },
  { code: "561920", title: "Convention and Trade Show Organizers", level: 6, parent: "561" },
  { code: "561591", title: "Convention and Visitors Bureaus", level: 6, parent: "561" },
  { code: "333922", title: "Conveyor and Conveying Equipment Manufacturing", level: 6, parent: "333" },
  { code: "311821", title: "Cookie and Cracker Manufacturing", level: 6, parent: "311" },
  { code: "331420", title: "Copper Rolling, Drawing, Extruding, and Alloying", level: 6, parent: "331" },
  { code: "212230", title: "Copper, Nickel, Lead, and Zinc Mining", level: 6, parent: "212" },
  { code: "111150", title: "Corn Farming", level: 6, parent: "111" },
  { code: "322211", title: "Corrugated and Solid Fiber Box Manufacturing", level: 6, parent: "322" },
  { code: "111920", title: "Cotton Farming", level: 6, parent: "111" },
  { code: "115111", title: "Cotton Ginning", level: 6, parent: "115" },
  { code: "561492", title: "Court Reporting and Stenotype Services", level: 6, parent: "561" },
  { code: "311512", title: "Creamery Butter Manufacturing", level: 6, parent: "311" },
  { code: "561450", title: "Credit Bureaus", level: 6, parent: "561" },
  { code: "115113", title: "Crop Harvesting, Primarily by Machine", level: 6, parent: "115" },
  { code: "211120", title: "Crude Petroleum Extraction", level: 6, parent: "211" },
  { code: "212313", title: "Crushed and Broken Granite Mining and Quarrying", level: 6, parent: "212" },
  { code: "212312", title: "Crushed and Broken Limestone Mining and Quarrying", level: 6, parent: "212" },
  { code: "335931", title: "Current-Carrying Wiring Device Manufacturing", level: 6, parent: "335" },
  { code: "314120", title: "Curtain and Linen Mills", level: 6, parent: "314" },
  { code: "337212", title: "Custom Architectural Woodwork and Millwork Manufacturing", level: 6, parent: "337" },
  { code: "325991", title: "Custom Compounding of Purchased Resins", level: 6, parent: "325" },
  { code: "332114", title: "Custom Roll Forming", level: 6, parent: "332" },
  { code: "321912", title: "Cut Stock, Resawing Lumber, and Planing", level: 6, parent: "321" },
  { code: "327991", title: "Cut Stone and Stone Product Manufacturing", level: 6, parent: "327" },
  { code: "315210", title: "Cut and Sew Apparel Contractors", level: 6, parent: "315" },
  { code: "315250", title: "Cut and Sew Apparel Manufacturing (except Contractors)", level: 6, parent: "315" },
  { code: "333515", title: "Cutting Tool and Machine Tool Accessory Manufacturing", level: 6, parent: "333" },
  { code: "325194", title: "Cyclic Crude, Intermediate, and Gum and Wood Chemical Manufacturing", level: 6, parent: "325" },
  { code: "112120", title: "Dairy Cattle and Milk Production", level: 6, parent: "112" },
  { code: "483111", title: "Deep Sea Freight Transportation", level: 6, parent: "483" },
  { code: "483112", title: "Deep Sea Passenger Transportation", level: 6, parent: "483" },
  { code: "339114", title: "Dental Equipment and Supplies Manufacturing", level: 6, parent: "339" },
  { code: "339116", title: "Dental Laboratories", level: 6, parent: "339" },
  { code: "212311", title: "Dimension Stone Mining and Quarrying", level: 6, parent: "212" },
  { code: "312140", title: "Distilleries", level: 6, parent: "312" },
  { code: "561410", title: "Document Preparation Services", level: 6, parent: "561" },
  { code: "311111", title: "Dog and Cat Food Manufacturing", level: 6, parent: "311" },
  { code: "339930", title: "Doll, Toy, and Game Manufacturing", level: 6, parent: "339" },
  { code: "311423", title: "Dried and Dehydrated Food Manufacturing", level: 6, parent: "311" },
  { code: "213111", title: "Drilling Oil and Gas Wells", level: 6, parent: "213" },
  { code: "311824", title: "Dry Pasta, Dough, and Flour Mixes Manufacturing from Purchased Flour", level: 6, parent: "311" },
  { code: "111130", title: "Dry Pea and Bean Farming", level: 6, parent: "111" },
  { code: "311514", title: "Dry, Condensed, and Evaporated Dairy Product Manufacturing", level: 6, parent: "311" },
  { code: "238310", title: "Drywall and Insulation Contractors", level: 6, parent: "238" },
  { code: "112130", title: "Dual-Purpose Cattle Ranching and Farming", level: 6, parent: "112" },
  { code: "221121", title: "Electric Bulk Power Transmission and Control", level: 6, parent: "221" },
  { code: "335139", title: "Electric Lamp Bulb and Other Lighting Equipment Manufacturing", level: 6, parent: "335" },
  { code: "221122", title: "Electric Power Distribution", level: 6, parent: "221" },
  { code: "238210", title: "Electrical Contractors and Other Wiring Installation Contractors", level: 6, parent: "238" },
  { code: "334510", title: "Electromedical and Electrotherapeutic Apparatus Manufacturing", level: 6, parent: "334" },
  { code: "334111", title: "Electronic Computer Manufacturing", level: 6, parent: "334" },
  { code: "334417", title: "Electronic Connector Manufacturing", level: 6, parent: "334" },
  { code: "332813", title: "Electroplating, Plating, Polishing, Anodizing, and Coloring", level: 6, parent: "332" },
  { code: "333921", title: "Elevator and Moving Stairway Manufacturing", level: 6, parent: "333" },
  { code: "561311", title: "Employment Placement Agencies", level: 6, parent: "561" },
  { code: "321215", title: "Engineered Wood Member Manufacturing", level: 6, parent: "321" },
  { code: "325193", title: "Ethyl Alcohol Manufacturing", level: 6, parent: "325" },
  { code: "561312", title: "Executive Search Services", level: 6, parent: "561" },
  { code: "325920", title: "Explosives Manufacturing", level: 6, parent: "325" },
  { code: "561710", title: "Exterminating and Pest Control Services", level: 6, parent: "561" },
  { code: "313320", title: "Fabric Coating Mills", level: 6, parent: "313" },
  { code: "332996", title: "Fabricated Pipe and Pipe Fitting Manufacturing", level: 6, parent: "332" },
  { code: "332312", title: "Fabricated Structural Metal Manufacturing", level: 6, parent: "332" },
  { code: "561210", title: "Facilities Support Services", level: 6, parent: "561" },
  { code: "115115", title: "Farm Labor Contractors and Crew Leaders", level: 6, parent: "115" },
  { code: "333111", title: "Farm Machinery and Equipment Manufacturing", level: 6, parent: "333" },
  { code: "115116", title: "Farm Management Services", level: 6, parent: "115" },
  { code: "339993", title: "Fastener, Button, Needle, and Pin Manufacturing", level: 6, parent: "339" },
  { code: "311225", title: "Fats and Oils Refining and Blending", level: 6, parent: "311" },
  { code: "325314", title: "Fertilizer (Mixing Only) Manufacturing", level: 6, parent: "325" },
  { code: "335921", title: "Fiber Optic Cable Manufacturing", level: 6, parent: "335" },
  { code: "313110", title: "Fiber, Yarn, and Thread Mills", level: 6, parent: "313" },
  { code: "112511", title: "Finfish Farming and Fish Hatcheries", level: 6, parent: "112" },
  { code: "114111", title: "Finfish Fishing", level: 6, parent: "114" },
  { code: "238350", title: "Finish Carpentry Contractors", level: 6, parent: "238" },
  { code: "327211", title: "Flat Glass Manufacturing", level: 6, parent: "327" },
  { code: "311930", title: "Flavoring Syrup and Concentrate Manufacturing", level: 6, parent: "311" },
  { code: "238330", title: "Flooring Contractors", level: 6, parent: "238" },
  { code: "111422", title: "Floriculture Production", level: 6, parent: "111" },
  { code: "311211", title: "Flour Milling", level: 6, parent: "311" },
  { code: "311511", title: "Fluid Milk Manufacturing", level: 6, parent: "311" },
  { code: "333995", title: "Fluid Power Cylinder and Actuator Manufacturing", level: 6, parent: "333" },
  { code: "333996", title: "Fluid Power Pump and Motor Manufacturing", level: 6, parent: "333" },
  { code: "332912", title: "Fluid Power Valve and Hose Fitting Manufacturing", level: 6, parent: "332" },
  { code: "322212", title: "Folding Paperboard Box Manufacturing", level: 6, parent: "322" },
  { code: "333241", title: "Food Product Machinery Manufacturing", level: 6, parent: "333" },
  { code: "316210", title: "Footwear Manufacturing", level: 6, parent: "316" },
  { code: "113210", title: "Forest Nurseries and Gathering of Forest Products", level: 6, parent: "113" },
  { code: "221112", title: "Fossil Fuel Electric Power Generation", level: 6, parent: "221" },
  { code: "238130", title: "Framing Contractors", level: 6, parent: "238" },
  { code: "488510", title: "Freight Transportation Arrangement", level: 6, parent: "488" },
  { code: "311813", title: "Frozen Cakes, Pies, and Other Pastries Manufacturing", level: 6, parent: "311" },
  { code: "311411", title: "Frozen Fruit, Juice, and Vegetable Manufacturing", level: 6, parent: "311" },
  { code: "311412", title: "Frozen Specialty Food Manufacturing", level: 6, parent: "311" },
  { code: "111336", title: "Fruit and Tree Nut Combination Farming", level: 6, parent: "111" },
  { code: "311421", title: "Fruit and Vegetable Canning", level: 6, parent: "311" },
  { code: "112930", title: "Fur-Bearing Animal and Rabbit Production", level: 6, parent: "112" },
  { code: "339991", title: "Gasket, Packing, and Sealing Device Manufacturing", level: 6, parent: "339" },
  { code: "484110", title: "General Freight Trucking, Local", level: 6, parent: "484" },
  { code: "484122", title: "General Freight Trucking, Long-Distance, Less Than Truckload", level: 6, parent: "484" },
  { code: "484121", title: "General Freight Trucking, Long-Distance, Truckload", level: 6, parent: "484" },
  { code: "221116", title: "Geothermal Electric Power Generation", level: 6, parent: "221" },
  { code: "327213", title: "Glass Container Manufacturing", level: 6, parent: "327" },
  { code: "327215", title: "Glass Product Manufacturing Made of Purchased Glass", level: 6, parent: "327" },
  { code: "238150", title: "Glass and Glazing Contractors", level: 6, parent: "238" },
  { code: "112420", title: "Goat Farming", level: 6, parent: "112" },
  { code: "212220", title: "Gold Ore and Silver Ore Mining", level: 6, parent: "212" },
  { code: "111332", title: "Grape Vineyards", level: 6, parent: "111" },
  { code: "327992", title: "Ground or Treated Mineral and Earth Manufacturing", level: 6, parent: "327" },
  { code: "336414", title: "Guided Missile and Space Vehicle Manufacturing", level: 6, parent: "336" },
  { code: "336415", title: "Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing", level: 6, parent: "336" },
  { code: "327420", title: "Gypsum Product Manufacturing", level: 6, parent: "327" },
  { code: "332510", title: "Hardware Manufacturing", level: 6, parent: "332" },
  { code: "321211", title: "Hardwood Veneer and Plywood Manufacturing", level: 6, parent: "321" },
  { code: "111940", title: "Hay Farming", level: 6, parent: "111" },
  { code: "562112", title: "Hazardous Waste Collection", level: 6, parent: "562" },
  { code: "562211", title: "Hazardous Waste Treatment and Disposal", level: 6, parent: "562" },
  { code: "333414", title: "Heating Equipment (except Warm Air Furnaces) Manufacturing", level: 6, parent: "333" },
  { code: "336120", title: "Heavy Duty Truck Manufacturing", level: 6, parent: "336" },
  { code: "237310", title: "Highway, Street, and Bridge Construction", level: 6, parent: "237" },
  { code: "112210", title: "Hog and Pig Farming", level: 6, parent: "112" },
  { code: "112920", title: "Horses and Other Equine Production", level: 6, parent: "112" },
  { code: "337126", title: "Household Furniture (except Wood and Upholstered) Manufacturing", level: 6, parent: "337" },
  { code: "114210", title: "Hunting and Trapping", level: 6, parent: "114" },
  { code: "221111", title: "Hydroelectric Power Generation", level: 6, parent: "221" },
  { code: "311520", title: "Ice Cream and Frozen Dessert Manufacturing", level: 6, parent: "311" },
  { code: "312113", title: "Ice Manufacturing", level: 6, parent: "312" },
  { code: "325413", title: "In-Vitro Diagnostic Substance Manufacturing", level: 6, parent: "325" },
  { code: "236210", title: "Industrial Building Construction", level: 6, parent: "236" },
  { code: "325120", title: "Industrial Gas Manufacturing", level: 6, parent: "325" },
  { code: "333511", title: "Industrial Mold Manufacturing", level: 6, parent: "333" },
  { code: "333994", title: "Industrial Process Furnace and Oven Manufacturing", level: 6, parent: "333" },
  { code: "212322", title: "Industrial Sand Mining", level: 6, parent: "212" },
  { code: "333924", title: "Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing", level: 6, parent: "333" },
  { code: "332911", title: "Industrial Valve Manufacturing", level: 6, parent: "332" },
  { code: "333413", title: "Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing", level: 6, parent: "333" },
  { code: "483211", title: "Inland Water Freight Transportation", level: 6, parent: "483" },
  { code: "483212", title: "Inland Water Passenger Transportation", level: 6, parent: "483" },
  { code: "337127", title: "Institutional Furniture Manufacturing", level: 6, parent: "337" },
  { code: "334515", title: "Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals", level: 6, parent: "334" },
  { code: "334513", title: "Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables", level: 6, parent: "334" },
  { code: "485210", title: "Interurban and Rural Bus Transportation", level: 6, parent: "485" },
  { code: "561611", title: "Investigation and Personal Background Check Services", level: 6, parent: "561" },
  { code: "331511", title: "Iron Foundries", level: 6, parent: "331" },
  { code: "212210", title: "Iron Ore Mining", level: 6, parent: "212" },
  { code: "332111", title: "Iron and Steel Forging", level: 6, parent: "332" },
  { code: "331110", title: "Iron and Steel Mills and Ferroalloy Manufacturing", level: 6, parent: "331" },
  { code: "331210", title: "Iron and Steel Pipe and Tube Manufacturing from Purchased Steel", level: 6, parent: "331" },
  { code: "334517", title: "Irradiation Apparatus Manufacturing", level: 6, parent: "334" },
  { code: "561720", title: "Janitorial Services", level: 6, parent: "561" },
  { code: "339910", title: "Jewelry and Silverware Manufacturing", level: 6, parent: "339" },
  { code: "212323", title: "Kaolin, Clay, and Ceramic and Refractory Minerals Mining", level: 6, parent: "212" },
  { code: "313240", title: "Knit Fabric Mills", level: 6, parent: "313" },
  { code: "326130", title: "Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing", level: 6, parent: "326" },
  { code: "237210", title: "Land Subdivision", level: 6, parent: "237" },
  { code: "561730", title: "Landscaping Services", level: 6, parent: "561" },
  { code: "333112", title: "Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing", level: 6, parent: "333" },
  { code: "316110", title: "Leather and Hide Tanning and Finishing", level: 6, parent: "316" },
  { code: "327410", title: "Lime Manufacturing", level: 6, parent: "327" },
  { code: "485320", title: "Limousine Service", level: 6, parent: "485" },
  { code: "482111", title: "Line-Haul Railroads", level: 6, parent: "482" },
  { code: "561622", title: "Locksmiths", level: 6, parent: "561" },
  { code: "113310", title: "Logging", level: 6, parent: "113" },
  { code: "332710", title: "Machine Shops", level: 6, parent: "332" },
  { code: "333517", title: "Machine Tool Manufacturing", level: 6, parent: "333" },
  { code: "335220", title: "Major Household Appliance Manufacturing", level: 6, parent: "335" },
  { code: "311213", title: "Malt Manufacturing", level: 6, parent: "311" },
  { code: "321991", title: "Manufactured Home (Mobile Home) Manufacturing", level: 6, parent: "321" },
  { code: "334610", title: "Manufacturing and Reproducing Magnetic and Optical Media", level: 6, parent: "334" },
  { code: "488320", title: "Marine Cargo Handling", level: 6, parent: "488" },
  { code: "238140", title: "Masonry Contractors", level: 6, parent: "238" },
  { code: "562920", title: "Materials Recovery Facilities", level: 6, parent: "562" },
  { code: "337910", title: "Mattress Manufacturing", level: 6, parent: "337" },
  { code: "311941", title: "Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing", level: 6, parent: "311" },
  { code: "333914", title: "Measuring, Dispensing, and Other Pumping Equipment Manufacturing", level: 6, parent: "333" },
  { code: "311612", title: "Meat Processed from Carcasses", level: 6, parent: "311" },
  { code: "333613", title: "Mechanical Power Transmission Equipment Manufacturing", level: 6, parent: "333" },
  { code: "325411", title: "Medicinal and Botanical Manufacturing", level: 6, parent: "325" },
  { code: "332431", title: "Metal Can Manufacturing", level: 6, parent: "332" },
  { code: "332812", title: "Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers", level: 6, parent: "332" },
  { code: "332119", title: "Metal Crown, Closure, and Other Metal Stamping (except Automotive)", level: 6, parent: "332" },
  { code: "332811", title: "Metal Heat Treating", level: 6, parent: "332" },
  { code: "332215", title: "Metal Kitchen Cookware, Utensil, Cutlery, and Flatware (except Precious) Manufacturing", level: 6, parent: "332" },
  { code: "332420", title: "Metal Tank (Heavy Gauge) Manufacturing", level: 6, parent: "332" },
  { code: "332321", title: "Metal Window and Door Manufacturing", level: 6, parent: "332" },
  { code: "336992", title: "Military Armored Vehicle, Tank, and Tank Component Manufacturing", level: 6, parent: "336" },
  { code: "327993", title: "Mineral Wool Manufacturing", level: 6, parent: "327" },
  { code: "333131", title: "Mining Machinery and Equipment Manufacturing", level: 6, parent: "333" },
  { code: "485111", title: "Mixed Mode Transit Systems", level: 6, parent: "485" },
  { code: "336213", title: "Motor Home Manufacturing", level: 6, parent: "336" },
  { code: "336211", title: "Motor Vehicle Body Manufacturing", level: 6, parent: "336" },
  { code: "336340", title: "Motor Vehicle Brake System Manufacturing", level: 6, parent: "336" },
  { code: "336320", title: "Motor Vehicle Electrical and Electronic Equipment Manufacturing", level: 6, parent: "336" },
  { code: "336310", title: "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing", level: 6, parent: "336" },
  { code: "336370", title: "Motor Vehicle Metal Stamping", level: 6, parent: "336" },
  { code: "336360", title: "Motor Vehicle Seating and Interior Trim Manufacturing", level: 6, parent: "336" },
  { code: "336330", title: "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing", level: 6, parent: "336" },
  { code: "488410", title: "Motor Vehicle Towing", level: 6, parent: "488" },
  { code: "336350", title: "Motor Vehicle Transmission and Power Train Parts Manufacturing", level: 6, parent: "336" },
  { code: "335312", title: "Motor and Generator Manufacturing", level: 6, parent: "335" },
  { code: "336991", title: "Motorcycle, Bicycle, and Parts Manufacturing", level: 6, parent: "336" },
  { code: "111411", title: "Mushroom Production", level: 6, parent: "111" },
  { code: "339992", title: "Musical Instrument Manufacturing", level: 6, parent: "339" },
  { code: "313220", title: "Narrow Fabric Mills and Schiffli Machine Embroidery", level: 6, parent: "313" },
  { code: "221210", title: "Natural Gas Distribution", level: 6, parent: "221" },
  { code: "211130", title: "Natural Gas Extraction", level: 6, parent: "211" },
  { code: "488330", title: "Navigational Services to Shipping", level: 6, parent: "488" },
  { code: "236117", title: "New Housing For-Sale Builders", level: 6, parent: "236" },
  { code: "236116", title: "New Multifamily Housing Construction (except For-Sale Builders)", level: 6, parent: "236" },
  { code: "236115", title: "New Single-Family Housing Construction (except For-Sale Builders)", level: 6, parent: "236" },
  { code: "325311", title: "Nitrogenous Fertilizer Manufacturing", level: 6, parent: "325" },
  { code: "311340", title: "Nonchocolate Confectionery Manufacturing", level: 6, parent: "311" },
  { code: "335932", title: "Noncurrent-Carrying Wiring Device Manufacturing", level: 6, parent: "335" },
  { code: "332112", title: "Nonferrous Forging", level: 6, parent: "332" },
  { code: "331410", title: "Nonferrous Metal (except Aluminum) Smelting and Refining", level: 6, parent: "331" },
  { code: "331491", title: "Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding", level: 6, parent: "331" },
  { code: "331523", title: "Nonferrous Metal Die-Casting Foundries", level: 6, parent: "331" },
  { code: "481212", title: "Nonscheduled Chartered Freight Air Transportation", level: 6, parent: "481" },
  { code: "481211", title: "Nonscheduled Chartered Passenger Air Transportation", level: 6, parent: "481" },
  { code: "337122", title: "Nonupholstered Wood Household Furniture Manufacturing", level: 6, parent: "337" },
  { code: "313230", title: "Nonwoven Fabric Mills", level: 6, parent: "313" },
  { code: "221113", title: "Nuclear Electric Power Generation", level: 6, parent: "221" },
  { code: "111421", title: "Nursery and Tree Production", level: 6, parent: "111" },
  { code: "561110", title: "Office Administrative Services", level: 6, parent: "561" },
  { code: "337214", title: "Office Furniture (except Wood) Manufacturing", level: 6, parent: "337" },
  { code: "339940", title: "Office Supplies (except Paper) Manufacturing", level: 6, parent: "339" },
  { code: "333132", title: "Oil and Gas Field Machinery and Equipment Manufacturing", level: 6, parent: "333" },
  { code: "237120", title: "Oil and Gas Pipeline and Related Structures Construction", level: 6, parent: "237" },
  { code: "111120", title: "Oilseed (except Soybean) Farming", level: 6, parent: "111" },
  { code: "111191", title: "Oilseed and Grain Combination Farming", level: 6, parent: "111" },
  { code: "339115", title: "Ophthalmic Goods Manufacturing", level: 6, parent: "339" },
  { code: "111310", title: "Orange Groves", level: 6, parent: "111" },
  { code: "332323", title: "Ornamental and Architectural Metal Work Manufacturing", level: 6, parent: "332" },
  { code: "336413", title: "Other Aircraft Parts and Auxiliary Equipment Manufacturing", level: 6, parent: "336" },
  { code: "488119", title: "Other Airport Operations", level: 6, parent: "488" },
  { code: "331318", title: "Other Aluminum Rolling, Drawing, and Extruding", level: 6, parent: "331" },
  { code: "311119", title: "Other Animal Food Manufacturing", level: 6, parent: "311" },
  { code: "112519", title: "Other Aquaculture", level: 6, parent: "112" },
  { code: "325180", title: "Other Basic Inorganic Chemical Manufacturing", level: 6, parent: "325" },
  { code: "238290", title: "Other Building Equipment Contractors", level: 6, parent: "238" },
  { code: "238390", title: "Other Building Finishing Contractors", level: 6, parent: "238" },
  { code: "561439", title: "Other Business Service Centers (including Copy Shops)", level: 6, parent: "561" },
  { code: "335929", title: "Other Communication and Energy Wire Manufacturing", level: 6, parent: "335" },
  { code: "334290", title: "Other Communications Equipment Manufacturing", level: 6, parent: "334" },
  { code: "327390", title: "Other Concrete Product Manufacturing", level: 6, parent: "327" },
  { code: "212319", title: "Other Crushed and Broken Stone Mining and Quarrying", level: 6, parent: "212" },
  { code: "221118", title: "Other Electric Power Generation", level: 6, parent: "221" },
  { code: "334419", title: "Other Electronic Component Manufacturing", level: 6, parent: "334" },
  { code: "333618", title: "Other Engine Equipment Manufacturing", level: 6, parent: "333" },
  { code: "332618", title: "Other Fabricated Wire Product Manufacturing", level: 6, parent: "332" },
  { code: "111419", title: "Other Food Crops Grown Under Cover", level: 6, parent: "111" },
  { code: "238190", title: "Other Foundation, Structure, and Building Exterior Contractors", level: 6, parent: "238" },
  { code: "336419", title: "Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment Manufacturing", level: 6, parent: "336" },
  { code: "237990", title: "Other Heavy and Civil Engineering Construction", level: 6, parent: "237" },
  { code: "316990", title: "Other Leather and Allied Product Manufacturing", level: 6, parent: "316" },
  { code: "114119", title: "Other Marine Fishing", level: 6, parent: "114" },
  { code: "334519", title: "Other Measuring and Controlling Device Manufacturing", level: 6, parent: "334" },
  { code: "332439", title: "Other Metal Container Manufacturing", level: 6, parent: "332" },
  { code: "212290", title: "Other Metal Ore Mining", level: 6, parent: "212" },
  { code: "332919", title: "Other Metal Valve and Pipe Fitting Manufacturing", level: 6, parent: "332" },
  { code: "321918", title: "Other Millwork (including Flooring)", level: 6, parent: "321" },
  { code: "336390", title: "Other Motor Vehicle Parts Manufacturing", level: 6, parent: "336" },
  { code: "111339", title: "Other Noncitrus Fruit Farming", level: 6, parent: "111" },
  { code: "331529", title: "Other Nonferrous Metal Foundries (except Die-Casting)", level: 6, parent: "331" },
  { code: "562219", title: "Other Nonhazardous Waste Treatment and Disposal", level: 6, parent: "562" },
  { code: "212390", title: "Other Nonmetallic Mineral Mining and Quarrying", level: 6, parent: "212" },
  { code: "481219", title: "Other Nonscheduled Air Transportation", level: 6, parent: "481" },
  { code: "322219", title: "Other Paperboard Container Manufacturing", level: 6, parent: "322" },
  { code: "112390", title: "Other Poultry Production", level: 6, parent: "112" },
  { code: "327212", title: "Other Pressed and Blown Glass and Glassware Manufacturing", level: 6, parent: "327" },
  { code: "561790", title: "Other Services to Buildings and Dwellings", level: 6, parent: "561" },
  { code: "311919", title: "Other Snack Food Manufacturing", level: 6, parent: "311" },
  { code: "488190", title: "Other Support Activities for Air Transportation", level: 6, parent: "488" },
  { code: "488490", title: "Other Support Activities for Road Transportation", level: 6, parent: "488" },
  { code: "488390", title: "Other Support Activities for Water Transportation", level: 6, parent: "488" },
  { code: "485119", title: "Other Urban Transit Systems", level: 6, parent: "485" },
  { code: "111219", title: "Other Vegetable (except Potato) and Melon Farming", level: 6, parent: "111" },
  { code: "562119", title: "Other Waste Collection", level: 6, parent: "562" },
  { code: "333923", title: "Overhead Traveling Crane, Hoist, and Monorail System Manufacturing", level: 6, parent: "333" },
  { code: "333993", title: "Packaging Machinery Manufacturing", level: 6, parent: "333" },
  { code: "561910", title: "Packaging and Labeling Services", level: 6, parent: "561" },
  { code: "488991", title: "Packing and Crating", level: 6, parent: "488" },
  { code: "325510", title: "Paint and Coating Manufacturing", level: 6, parent: "325" },
  { code: "238320", title: "Painting and Wall Covering Contractors", level: 6, parent: "238" },
  { code: "322220", title: "Paper Bag and Coated and Treated Paper Manufacturing", level: 6, parent: "322" },
  { code: "322120", title: "Paper Mills", level: 6, parent: "322" },
  { code: "322130", title: "Paperboard Mills", level: 6, parent: "322" },
  { code: "111992", title: "Peanut Farming", level: 6, parent: "111" },
  { code: "311991", title: "Perishable Prepared Food Manufacturing", level: 6, parent: "311" },
  { code: "325320", title: "Pesticide and Other Agricultural Chemical Manufacturing", level: 6, parent: "325" },
  { code: "325110", title: "Petrochemical Manufacturing", level: 6, parent: "325" },
  { code: "324191", title: "Petroleum Lubricating Oil and Grease Manufacturing", level: 6, parent: "324" },
  { code: "324110", title: "Petroleum Refineries", level: 6, parent: "324" },
  { code: "325412", title: "Pharmaceutical Preparation Manufacturing", level: 6, parent: "325" },
  { code: "325312", title: "Phosphatic Fertilizer Manufacturing", level: 6, parent: "325" },
  { code: "325992", title: "Photographic Film, Paper, Plate, Chemical, and Copy Toner Manufacturing", level: 6, parent: "325" },
  { code: "486110", title: "Pipeline Transportation of Crude Oil", level: 6, parent: "486" },
  { code: "486210", title: "Pipeline Transportation of Natural Gas", level: 6, parent: "486" },
  { code: "486910", title: "Pipeline Transportation of Refined Petroleum Products", level: 6, parent: "486" },
  { code: "326111", title: "Plastics Bag and Pouch Manufacturing", level: 6, parent: "326" },
  { code: "326160", title: "Plastics Bottle Manufacturing", level: 6, parent: "326" },
  { code: "325211", title: "Plastics Material and Resin Manufacturing", level: 6, parent: "325" },
  { code: "326112", title: "Plastics Packaging Film and Sheet (including Laminated) Manufacturing", level: 6, parent: "326" },
  { code: "326122", title: "Plastics Pipe and Pipe Fitting Manufacturing", level: 6, parent: "326" },
  { code: "326191", title: "Plastics Plumbing Fixture Manufacturing", level: 6, parent: "326" },
  { code: "332313", title: "Plate Work Manufacturing", level: 6, parent: "332" },
  { code: "332913", title: "Plumbing Fixture Fitting and Trim Manufacturing", level: 6, parent: "332" },
  { code: "238220", title: "Plumbing, Heating, and Air-Conditioning Contractors", level: 6, parent: "238" },
  { code: "325612", title: "Polish and Other Sanitation Good Manufacturing", level: 6, parent: "325" },
  { code: "326140", title: "Polystyrene Foam Product Manufacturing", level: 6, parent: "326" },
  { code: "488310", title: "Port and Harbor Operations", level: 6, parent: "488" },
  { code: "115114", title: "Postharvest Crop Activities (except Cotton Ginning)", level: 6, parent: "115" },
  { code: "111211", title: "Potato Farming", level: 6, parent: "111" },
  { code: "327110", title: "Pottery, Ceramics, and Plumbing Fixture Manufacturing", level: 6, parent: "327" },
  { code: "112340", title: "Poultry Hatcheries", level: 6, parent: "112" },
  { code: "311615", title: "Poultry Processing", level: 6, parent: "311" },
  { code: "238110", title: "Poured Concrete Foundation and Structure Contractors", level: 6, parent: "238" },
  { code: "332117", title: "Powder Metallurgy Part Manufacturing", level: 6, parent: "332" },
  { code: "332410", title: "Power Boiler and Heat Exchanger Manufacturing", level: 6, parent: "332" },
  { code: "237130", title: "Power and Communication Line and Related Structures Construction", level: 6, parent: "237" },
  { code: "335311", title: "Power, Distribution, and Specialty Transformer Manufacturing", level: 6, parent: "335" },
  { code: "333991", title: "Power-Driven Handtool Manufacturing", level: 6, parent: "333" },
  { code: "332721", title: "Precision Turned Product Manufacturing", level: 6, parent: "332" },
  { code: "332311", title: "Prefabricated Metal Building and Component Manufacturing", level: 6, parent: "332" },
  { code: "321992", title: "Prefabricated Wood Building Manufacturing", level: 6, parent: "321" },
  { code: "334418", title: "Printed Circuit Assembly (Electronic Assembly) Manufacturing", level: 6, parent: "334" },
  { code: "325910", title: "Printing Ink Manufacturing", level: 6, parent: "325" },
  { code: "561431", title: "Private Mail Centers", level: 6, parent: "561" },
  { code: "561330", title: "Professional Employer Organizations", level: 6, parent: "561" },
  { code: "322110", title: "Pulp Mills", level: 6, parent: "322" },
  { code: "334220", title: "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing", level: 6, parent: "334" },
  { code: "336510", title: "Railroad Rolling Stock Manufacturing", level: 6, parent: "336" },
  { code: "327320", title: "Ready-Mix Concrete Manufacturing", level: 6, parent: "327" },
  { code: "321219", title: "Reconstituted Wood Product Manufacturing", level: 6, parent: "321" },
  { code: "335314", title: "Relay and Industrial Control Manufacturing", level: 6, parent: "335" },
  { code: "562910", title: "Remediation Services", level: 6, parent: "562" },
  { code: "311613", title: "Rendering and Meat Byproduct Processing", level: 6, parent: "311" },
  { code: "561491", title: "Repossession Services", level: 6, parent: "561" },
  { code: "335131", title: "Residential Electric Lighting Fixture Manufacturing", level: 6, parent: "335" },
  { code: "236118", title: "Residential Remodelers", level: 6, parent: "236" },
  { code: "311811", title: "Retail Bakeries", level: 6, parent: "311" },
  { code: "111160", title: "Rice Farming", level: 6, parent: "111" },
  { code: "311212", title: "Rice Milling", level: 6, parent: "311" },
  { code: "311911", title: "Roasted Nuts and Peanut Butter Manufacturing", level: 6, parent: "311" },
  { code: "331221", title: "Rolled Steel Shape Manufacturing", level: 6, parent: "331" },
  { code: "333519", title: "Rolling Mill and Other Metalworking Machinery Manufacturing", level: 6, parent: "333" },
  { code: "238160", title: "Roofing Contractors", level: 6, parent: "238" },
  { code: "314994", title: "Rope, Cordage, Twine, Tire Cord, and Tire Fabric Mills", level: 6, parent: "314" },
  { code: "326291", title: "Rubber Product Manufacturing for Mechanical Use", level: 6, parent: "326" },
  { code: "326220", title: "Rubber and Plastics Hoses and Belting Manufacturing", level: 6, parent: "326" },
  { code: "322291", title: "Sanitary Paper Product Manufacturing", level: 6, parent: "322" },
  { code: "332216", title: "Saw Blade and Handtool Manufacturing", level: 6, parent: "332" },
  { code: "333243", title: "Sawmill, Woodworking, and Paper Machinery Manufacturing", level: 6, parent: "333" },
  { code: "321113", title: "Sawmills", level: 6, parent: "321" },
  { code: "487110", title: "Scenic and Sightseeing Transportation, Land", level: 6, parent: "487" },
  { code: "487990", title: "Scenic and Sightseeing Transportation, Other", level: 6, parent: "487" },
  { code: "487210", title: "Scenic and Sightseeing Transportation, Water", level: 6, parent: "487" },
  { code: "481112", title: "Scheduled Freight Air Transportation", level: 6, parent: "481" },
  { code: "481111", title: "Scheduled Passenger Air Transportation", level: 6, parent: "481" },
  { code: "485410", title: "School and Employee Bus Transportation", level: 6, parent: "485" },
  { code: "311710", title: "Seafood Product Preparation and Packaging", level: 6, parent: "311" },
  { code: "334511", title: "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing", level: 6, parent: "334" },
  { code: "331314", title: "Secondary Smelting and Alloying of Aluminum", level: 6, parent: "331" },
  { code: "331492", title: "Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except Copper and Aluminum)", level: 6, parent: "331" },
  { code: "561612", title: "Security Guards and Patrol Services", level: 6, parent: "561" },
  { code: "561621", title: "Security Systems Services (except Locksmiths)", level: 6, parent: "561" },
  { code: "333242", title: "Semiconductor Machinery Manufacturing", level: 6, parent: "333" },
  { code: "334413", title: "Semiconductor and Related Device Manufacturing", level: 6, parent: "334" },
  { code: "562991", title: "Septic Tank and Related Services", level: 6, parent: "562" },
  { code: "221320", title: "Sewage Treatment Facilities", level: 6, parent: "221" },
  { code: "112410", title: "Sheep Farming", level: 6, parent: "112" },
  { code: "332322", title: "Sheet Metal Work Manufacturing", level: 6, parent: "332" },
  { code: "112512", title: "Shellfish Farming", level: 6, parent: "112" },
  { code: "114112", title: "Shellfish Fishing", level: 6, parent: "114" },
  { code: "336611", title: "Ship Building and Repairing", level: 6, parent: "336" },
  { code: "482112", title: "Short Line Railroads", level: 6, parent: "482" },
  { code: "337215", title: "Showcase, Partition, Shelving, and Locker Manufacturing", level: 6, parent: "337" },
  { code: "238170", title: "Siding Contractors", level: 6, parent: "238" },
  { code: "339950", title: "Sign Manufacturing", level: 6, parent: "339" },
  { code: "238910", title: "Site Preparation Contractors", level: 6, parent: "238" },
  { code: "332992", title: "Small Arms Ammunition Manufacturing", level: 6, parent: "332" },
  { code: "332994", title: "Small Arms, Ordnance, and Ordnance Accessories Manufacturing", level: 6, parent: "332" },
  { code: "335210", title: "Small Electrical Appliance Manufacturing", level: 6, parent: "335" },
  { code: "325611", title: "Soap and Other Detergent Manufacturing", level: 6, parent: "325" },
  { code: "312111", title: "Soft Drink Manufacturing", level: 6, parent: "312" },
  { code: "321212", title: "Softwood Veneer and Plywood Manufacturing", level: 6, parent: "321" },
  { code: "115112", title: "Soil Preparation, Planting, and Cultivating", level: 6, parent: "115" },
  { code: "221114", title: "Solar Electric Power Generation", level: 6, parent: "221" },
  { code: "562111", title: "Solid Waste Collection", level: 6, parent: "562" },
  { code: "562213", title: "Solid Waste Combustors and Incinerators", level: 6, parent: "562" },
  { code: "562212", title: "Solid Waste Landfill", level: 6, parent: "562" },
  { code: "111110", title: "Soybean Farming", level: 6, parent: "111" },
  { code: "311224", title: "Soybean and Other Oilseed Processing", level: 6, parent: "311" },
  { code: "333514", title: "Special Die and Tool, Die Set, Jig, and Fixture Manufacturing", level: 6, parent: "333" },
  { code: "485991", title: "Special Needs Transportation", level: 6, parent: "485" },
  { code: "484220", title: "Specialized Freight (except Used Goods) Trucking, Local", level: 6, parent: "484" },
  { code: "484230", title: "Specialized Freight (except Used Goods) Trucking, Long-Distance", level: 6, parent: "484" },
  { code: "311422", title: "Specialty Canning", level: 6, parent: "311" },
  { code: "333612", title: "Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing", level: 6, parent: "333" },
  { code: "311942", title: "Spice and Extract Manufacturing", level: 6, parent: "311" },
  { code: "339920", title: "Sporting and Athletic Goods Manufacturing", level: 6, parent: "339" },
  { code: "332613", title: "Spring Manufacturing", level: 6, parent: "332" },
  { code: "322230", title: "Stationery Product Manufacturing", level: 6, parent: "322" },
  { code: "221330", title: "Steam and Air-Conditioning Supply", level: 6, parent: "221" },
  { code: "331513", title: "Steel Foundries (except Investment)", level: 6, parent: "331" },
  { code: "331512", title: "Steel Investment Foundries", level: 6, parent: "331" },
  { code: "331222", title: "Steel Wire Drawing", level: 6, parent: "331" },
  { code: "111333", title: "Strawberry Farming", level: 6, parent: "111" },
  { code: "238120", title: "Structural Steel and Precast Concrete Contractors", level: 6, parent: "238" },
  { code: "111991", title: "Sugar Beet Farming", level: 6, parent: "111" },
  { code: "111930", title: "Sugarcane Farming", level: 6, parent: "111" },
  { code: "115210", title: "Support Activities for Animal Production", level: 6, parent: "115" },
  { code: "213113", title: "Support Activities for Coal Mining", level: 6, parent: "213" },
  { code: "115310", title: "Support Activities for Forestry", level: 6, parent: "115" },
  { code: "213114", title: "Support Activities for Metal Mining", level: 6, parent: "213" },
  { code: "213115", title: "Support Activities for Nonmetallic Minerals (except Fuels) Mining", level: 6, parent: "213" },
  { code: "213112", title: "Support Activities for Oil and Gas Operations", level: 6, parent: "213" },
  { code: "323120", title: "Support Activities for Printing", level: 6, parent: "323" },
  { code: "488210", title: "Support Activities for Rail Transportation", level: 6, parent: "488" },
  { code: "325613", title: "Surface Active Agent Manufacturing", level: 6, parent: "325" },
  { code: "212114", title: "Surface Coal Mining", level: 6, parent: "212" },
  { code: "339113", title: "Surgical Appliance and Supplies Manufacturing", level: 6, parent: "339" },
  { code: "339112", title: "Surgical and Medical Instrument Manufacturing", level: 6, parent: "339" },
  { code: "335313", title: "Switchgear and Switchboard Apparatus Manufacturing", level: 6, parent: "335" },
  { code: "325130", title: "Synthetic Dye and Pigment Manufacturing", level: 6, parent: "325" },
  { code: "325212", title: "Synthetic Rubber Manufacturing", level: 6, parent: "325" },
  { code: "485310", title: "Taxi and Ridesharing Services", level: 6, parent: "485" },
  { code: "561422", title: "Telemarketing Bureaus and Other Contact Centers", level: 6, parent: "561" },
  { code: "561421", title: "Telephone Answering Services", level: 6, parent: "561" },
  { code: "334210", title: "Telephone Apparatus Manufacturing", level: 6, parent: "334" },
  { code: "561320", title: "Temporary Help Services", level: 6, parent: "561" },
  { code: "314910", title: "Textile Bag and Canvas Mills", level: 6, parent: "314" },
  { code: "313310", title: "Textile and Fabric Finishing Mills", level: 6, parent: "313" },
  { code: "238340", title: "Tile and Terrazzo Contractors", level: 6, parent: "238" },
  { code: "113110", title: "Timber Tract Operations", level: 6, parent: "113" },
  { code: "326211", title: "Tire Manufacturing (except Retreading)", level: 6, parent: "326" },
  { code: "326212", title: "Tire Retreading", level: 6, parent: "326" },
  { code: "111910", title: "Tobacco Farming", level: 6, parent: "111" },
  { code: "312230", title: "Tobacco Manufacturing", level: 6, parent: "312" },
  { code: "325620", title: "Toilet Preparation Manufacturing", level: 6, parent: "325" },
  { code: "311830", title: "Tortilla Manufacturing", level: 6, parent: "311" },
  { code: "334514", title: "Totalizing Fluid Meter and Counting Device Manufacturing", level: 6, parent: "334" },
  { code: "561520", title: "Tour Operators", level: 6, parent: "561" },
  { code: "561510", title: "Travel Agencies", level: 6, parent: "561" },
  { code: "336214", title: "Travel Trailer and Camper Manufacturing", level: 6, parent: "336" },
  { code: "111335", title: "Tree Nut Farming", level: 6, parent: "111" },
  { code: "336212", title: "Truck Trailer Manufacturing", level: 6, parent: "336" },
  { code: "333611", title: "Turbine and Turbine Generator Set Units Manufacturing", level: 6, parent: "333" },
  { code: "112330", title: "Turkey Production", level: 6, parent: "112" },
  { code: "212115", title: "Underground Coal Mining", level: 6, parent: "212" },
  { code: "326113", title: "Unlaminated Plastics Film and Sheet (except Packaging) Manufacturing", level: 6, parent: "326" },
  { code: "326121", title: "Unlaminated Plastics Profile Shape Manufacturing", level: 6, parent: "326" },
  { code: "337121", title: "Upholstered Household Furniture Manufacturing", level: 6, parent: "337" },
  { code: "326150", title: "Urethane and Other Foam Product (except Polystyrene) Manufacturing", level: 6, parent: "326" },
  { code: "484210", title: "Used Household and Office Goods Moving", level: 6, parent: "484" },
  { code: "221310", title: "Water Supply and Irrigation Systems", level: 6, parent: "221" },
  { code: "237110", title: "Water and Sewer Line and Related Structures Construction", level: 6, parent: "237" },
  { code: "333992", title: "Welding and Soldering Equipment Manufacturing", level: 6, parent: "333" },
  { code: "311221", title: "Wet Corn Milling and Starch Manufacturing", level: 6, parent: "311" },
  { code: "111140", title: "Wheat Farming", level: 6, parent: "111" },
  { code: "221115", title: "Wind Electric Power Generation", level: 6, parent: "221" },
  { code: "312130", title: "Wineries", level: 6, parent: "312" },
  { code: "321920", title: "Wood Container and Pallet Manufacturing", level: 6, parent: "321" },
  { code: "337110", title: "Wood Kitchen Cabinet and Countertop Manufacturing", level: 6, parent: "337" },
  { code: "337211", title: "Wood Office Furniture Manufacturing", level: 6, parent: "337" },
  { code: "321114", title: "Wood Preservation", level: 6, parent: "321" },
  { code: "321911", title: "Wood Window and Door Manufacturing", level: 6, parent: "321" },
];

// Helper functions for NAICS lookups
export function getFacilityCategoriesBySector(sectorCode: string): NAICSCode[] {
  return FACILITY_CATEGORIES.filter(category => category.parent === sectorCode)
    .sort((a, b) => a.title.localeCompare(b.title));
}

export function getFacilityTypesByCategory(categoryCode: string): NAICSCode[] {
  return FACILITY_TYPES.filter(type => type.parent === categoryCode)
    .sort((a, b) => a.title.localeCompare(b.title));
}

export function generateNAICSCode(sectorCode: string, categoryCode: string, typeCode: string): string {
  const sector = FACILITY_SECTORS.find(s => s.code === sectorCode);
  const category = FACILITY_CATEGORIES.find(c => c.code === categoryCode && c.parent === sectorCode);
  const type = FACILITY_TYPES.find(t => t.code === typeCode && t.parent === categoryCode);
  
  if (!sector || !category || !type) {
    throw new Error('Invalid NAICS code combination');
  }
  
  return typeCode;
}

export function getNAICSDescription(naicsCode: string): string {
  const type = FACILITY_TYPES.find(t => t.code === naicsCode);
  if (type) {
    const category = FACILITY_CATEGORIES.find(c => c.code === type.parent);
    const sector = FACILITY_SECTORS.find(s => s.code === category?.parent);
    return `${sector?.title} > ${category?.title} > ${type.title}`;
  }
  return 'Unknown NAICS code';
}
